# Location to store the data. 
# ../ is used because the script that downloads the data is located in the script/ folder.
datadir: '../data/'
geojson: 'data/provinces.geojson'
covid_data: "data/time_series_covid19_confirmed_global.csv"
urls: {
  "2020": "https://data.rivm.nl/data/luchtmeetnet/Vastgesteld-jaar/2020/",
  "2021": "https://data.rivm.nl/data/luchtmeetnet/Actueel-jaar/"
}

# Location of the data directory 
data: './data/'
