name: DSLS_prog1_final
channels:
  - defaults
  - conda-forge
  - bokeh
dependencies:
  - scipy
  - statsmodels
  - jupyter
  - scikit-learn
  - numpy
  - panel
  - bokeh
  - regex=
  - pathlib
  - pandas
  - matplotlib
  - requests
  - pyyaml
  - python
  - pyopenssl
  - certifi
  - bs4
  - tqdm
  - holoviews
  - hvplot
  - folium
  - branca
