name: DSLS_prog_final
channels:
  - defaults
  - conda-forge
  - bokeh
dependencies:
  - scipy=1.7.1
  - statsmodels=0.13.0
  - jupyter=1.0.0
  - scikit-learn=1.0.1
  - numpy=1.21.2
  - panel=0.12.1
  - bokeh=2.3.3
  - regex=2021.11.10
  - pathlib=1.0.1
  - pandas=1.3.4
  - matplotlib=3.5.0
  - requests=2.27.1
  - pyyaml=6.0
  - python=3.9.7
  - pyopenssl=21.0.0
  - certifi=2021.10.8
  - bs4=4.10.0
  - progressbar=2.5
  - tqdm=4.62.3
  - holoviews=1.12.7
  - hvplot=0.7.3
  - folium=0.12.1.post1
  - branca=0.4.2
  